title: AppleMoss
description:
owner: AppleMoss
first_published: 2018
email: your-email@domain.com
baseurl: ""
url: "https://applemoss.com"
social:
  twitter: https://twitter.com/applemoss
  facebook: https://facebook.com/applemoss
  google-plus: https://plus.google.com/u/0/+applemoss
  email: mailto:info@applemoss.com

plugins:
  - jekyll-seo-tag

markdown: kramdown
sass:
 style: compressed
